version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    container_name: rosegarden_theme1_wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: rosegarden_theme1_db
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: rosegarden_theme1_mysql
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rosegarden_theme1_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: rosegarden_theme1_phpmyadmin
    restart: always
    depends_on:
      - db 
    ports:
      - 8888:80

volumes:
  db_data: